### ISSUE TITLE
Consider open admin pages to committee members after deadline

### ISSUE THREAD

**Issue by cherrybeans** [webkom/admissions#147]
Could be nice to allow the other members of a committee to see the admissions online after the deadline has passed, since they get it from their leader anyway.

**Comment by cherrybeans** [comment]
@JonasBak How about this? Could be nice to have, but not necessary.

**Comment by JonasBak** [comment]
I don't really see this as a big problem, and it's imo nice that the leader has control over the applications.

**Comment by norbye** [comment]
Don't want to
