### ISSUE TITLE
Make it possible to close admission from admin panel

### ISSUE THREAD

**Issue by cherrybeans** [webkom/admissions#7]

**Comment by erlingfn** [comment]
Is this functionality we want? As of now an admission is not explicitly closed, but closes whenever the deadline is passed. Do we instead want to be able to change the deadline?

**Comment by norbye** [comment]
Resolved by #877 (in the way that it is now possible to change the deadlines from the adminpanel, and thus possible to change the deadline to a past time - effectively closing it)
